# -*- coding: utf-8 -*-
"""movie recommandations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_y5GeHOLgCjjQ3DUDoLpcW9xqQw6GCgJ
"""

import pandas as pd
movies_df = pd.read_csv("/content/sample_data/tmdb_5000_movies.csv")
credits_df= pd.read_csv("/content/sample_data/tmdb_5000_credits.csv")
print(movies_df.head())
print(credits_df.head())

credits_df.rename(columns={"movie_id": "id"},inplace=True)
print(credits_df.info())

result_df= pd.merge(movies_df,credits_df,on ="id")
print(result_df.shape)

result_df.drop(["homepage","production_companies","title_x","title_y"],axis=1,inplace=True)
print(result_df.shape)

result_df.dropna(inplace=True)
print(result_df.shape)

v=result_df["vote_count"]
R= result_df["vote_average"]
m= result_df["vote_count"].quantile(0.9)
C= result_df["vote_average"].mean()
result_df["weighted_rating"]=(R*v+m*C)/(v+m)
print(result_df[["original_title","weighted_rating"]])
result_df.sort_values("weighted_rating",ascending=False,inplace=True)
print(result_df[["original_title","weighted_rating"]].head(10))

import matplotlib.pyplot as plt
fig,ax=plt.subplots(figsize=(8,6))
res_df_sorted= result_df.head(10).sort_values("weighted_rating")
ax.barh(res_df_sorted["original_title"],res_df_sorted["weighted_rating"],color="purple")
ax.set_xlabel("weighted rating")
ax.set_ylabel("Movie Title")
ax.set_title("Top 10 Movies by weighted rating")
plt.tight_layout()
plt.show()